# Generated by Django 2.2.3 on 2019-07-12 09:32

import beerFriends.models
import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('addedOn', models.DateField(blank=True, default=datetime.datetime.now)),
                ('origin', models.CharField(max_length=250, null=True)),
                ('rating', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/tylorborgeson/Workspaces/ReweDigital/beer-friends/media/images/'), upload_to=beerFriends.models.image_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('text', models.CharField(max_length=250, null=True)),
                ('creator', models.CharField(max_length=250, null=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerFriends.Beer')),
            ],
        ),
    ]
