# Generated by Django 2.2.3 on 2019-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerFriends', '0002_auto_20190712_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcoholContent',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
