# Generated by Django 2.2.3 on 2019-07-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerFriends', '0003_beer_alcoholcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='alcoholContent',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
