# Generated by Django 2.2.3 on 2019-07-26 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerFriends', '0004_auto_20190712_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
