# Generated by Django 2.2.3 on 2019-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerFriends', '0006_auto_20190726_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
